# Generated by Django 3.1.2 on 2021-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20210412_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='number_of_question',
            new_name='number_of_questions',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='required score in %'),
        ),
    ]
